function save_preprocessed_data_STIM(SubjectID, OUTPATH, SessionID, TaskID, StimSite,...
    channel_IDs, bad_channels, path_channels, exclusion_channels, out_channels,...
    bad_segments, white_channels, power_spectrum_deviant_channels, loud_channels, ...
    bad_epochs, Stim1, Stim2, Z_data, CurrentID)
%% add paths
addpath('/projects/b1134/tools/eegpreproc/helper_functions/STIM')

%% save preprocessed data
if sum(isletter(SubjectID)) == length(SubjectID) && ~contains(OUTPATH, 'NWB')%for NU research data only
    fprintf('Deleting downsampled data file.\n')
    delete(sprintf('%s/downsampled_data_uV.mat', OUTPATH))
end

%broadband data
OUTFILE = sprintf('%s/sub-%s_ses-%s_task-%s_acq-%s-%s_ds_qcx_epoch_trialsx_bpref_z.mat',...
    OUTPATH, SubjectID, SessionID, TaskID, StimSite, CurrentID);
fprintf('Saving Preprocessed File\n %s \n', OUTFILE)
save(OUTFILE, 'channel_IDs', 'bad_channels', ...
    'path_channels', 'exclusion_channels', 'out_channels', 'bad_segments',...
    'white_channels', 'power_spectrum_deviant_channels', 'loud_channels', ...
    'bad_epochs','Stim1', 'Stim2', 'Z_data')

%flip CCEPs
CCEP_flip(OUTPATH)

%time-frequency data
%OUTFILE = sprintf('%s/sub-%s_ses-%s_task-%s_acq-%s-%s_ds_qcx_epoch_trialsx_bpref_tfd_z.mat',...
%    OUTPATH, SubjectID, SessionID, TaskID, StimSite, CurrentID);
%fprintf('Saving Preprocessed File\n %s \n', OUTFILE)
%save(OUTFILE, 'channel_IDs', 'bad_channels', ...
%    'path_channels', 'exclusion_channels', 'out_channels', 'bad_segments',...
%    'white_channels', 'power_spectrum_deviant_channels', 'loud_channels', ...
%    'bad_epochs','Stim1', 'Stim2', 'Z_timefreq_data')

end